client_config_backend: file
client_config:
    client_id: "548996040736-i4eaq7sp3nbu0m2hbkugecritu928q5v.apps.googleusercontent.com"
    client_secret: "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"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install